local M = {}

M.coastal_waters_waypoint = {
    name = "Coastal Waters Waypoint",
    type = "range",
    dice = "1d100",
    entries = {
        { min = 1, max = 2, result = "A wrecked ship or boat lies broken upon rocks" },
        { min = 3, max = 4, result = "Mist clings to a shoreline ruin" },
        { min = 5, max = 6, result = "Dancing ribbons of colorful lights appear in a dark sky" },
        { min = 7, max = 8, result = "The wind and waters are eerily calm" },
        { min = 9, max = 10, result = "A ship is anchored in a sheltered bay" },
        { min = 11, max = 12, result = "A wide river empties into the sea" },
        { min = 13, max = 14, result = "A large animal or beast watches from the shore" },
        { min = 15, max = 16, result = "A ship flounders in high seas" },
        { min = 17, max = 18, result = "A pod of orca glides past" },
        { min = 19, max = 20, result = "An abandoned settlement is partially reclaimed by the sea" },
        { min = 21, max = 22, result = "Waves break upon a wide rocky beach" },
        { min = 23, max = 24, result = "A beached ship is under repair" },
        { min = 25, max = 26, result = "The weather shifts, a portent of things to come" },
        { min = 27, max = 28, result = "A waterfall spills from a seaside bluff" },
        { min = 29, max = 30, result = "The skeletal ribs of an old wreck sit upon the shore" },
        { min = 31, max = 32, result = "Whalers or beast hunters prowl these waters in sleek ships" },
        { min = 33, max = 34, result = "A ruin lies half-submerged in shallow waters" },
        { min = 35, max = 36, result = "The water churns as a large school of fish flees a predator" },
        { min = 37, max = 38, result = "A bleak-looking island appears uninhabited" },
        { min = 39, max = 40, result = "A landed boat or ship sits upon the shore" },
        { min = 41, max = 42, result = "Imposing cliffs rise from the sea" },
        { min = 43, max = 44, result = "A dense fog clings to the water" },
        { min = 45, max = 46, result = "Boats and ships gather at a seaside settlement" },
        { min = 47, max = 48, result = "Hordes of seabirds nest upon a guano-spattered sea stack" },
        { min = 49, max = 50, result = "Whales crest the surface" },
        { min = 51, max = 52, result = "Laborers toil at a waterside worksite" },
        { min = 53, max = 54, result = "An ancient statue or monument stands on the shore" },
        { min = 55, max = 56, result = "Rocky shoals lie within shallow waters" },
        { min = 57, max = 58, result = "Just under the surface, a thick kelp forest dances in the current" },
        { min = 59, max = 60, result = "Fisher folk gather their catch" },
        { min = 61, max = 62, result = "A column of smoke rises from the interior of an island" },
        { min = 63, max = 64, result = "Gulls peck at a floating carcass" },
        { min = 65, max = 66, result = "A makeshift shelter or solitary home sits on the shore" },
        { min = 67, max = 68, result = "Darkness beckons from within a sea cave" },
        { min = 69, max = 70, result = "A storm gathers in the distance" },
        { min = 71, max = 72, result = "You spot a seaside camp or settlement" },
        { min = 73, max = 74, result = "Seals rest on a wave-swept rock" },
        { min = 75, max = 76, result = "A boat or ship comes into view" },
        { min = 77, max = 78, result = "The water stirs with the movement of a great creature" },
        { min = 79, max = 80, result = "Steep cliffs flank a narrow fjord" },
        { min = 81, max = 81, result = "A rogue iceberg drifts with the current" },
        { min = 82, max = 82, result = "A long line of ships appears on the horizon" },
        { min = 83, max = 83, result = "Sharks circle menacingly" },
        { min = 84, max = 84, result = "A capsized ship or boat drifts on the water" },
        { min = 85, max = 85, result = "A beacon tower glimmers with a warning flame" },
        { min = 86, max = 86, result = "Debris collects in a swirling eddy" },
        { min = 87, max = 87, result = "Eerie voices carry on the wind" },
        { min = 88, max = 88, result = "The temperature shifts unnaturally" },
        { min = 89, max = 89, result = "A shelf of glacial ice divides sea from land" },
        { min = 90, max = 90, result = "You spot ships engaged in a battle" },
        { min = 91, max = 91, result = "A lookout post or tower stands at water's edge" },
        { min = 92, max = 92, result = "A narrow channel leads through an icy expanse" },
        { min = 93, max = 93, result = "A whale corpse lies bloated on a beach" },
        { min = 94, max = 94, result = "A large natural arch towers over the surrounding waters" },
        { min = 95, max = 95, result = "A great flying creature circles overhead" },
        { min = 96, max = 96, result = "A bridge connects the mainland to an offshore island" },
        { min = 97, max = 97, result = "Mystic stones or strange pillars stand on the shore" },
        { min = 98, max = 98, result = "A stone fortification stands at water's edge" },
        { min = 99, max = 99, result = "Thickly-packed seaweed carpets the water" },
        { min = 100, max = 100, result = "A spectral manifestation appears" },
    }
}

return M