local M = {}

M.is_test_table = require("kleros.tables.is_test_table")
M.is_test_range_table = require("kleros.tables.is_test_range_table")
M.is_action = require("kleros.tables.is_action")
M.is_theme = require("kleros.tables.is_theme")
M.is_prompt_build = require("kleros.tables.is_prompt_build")
M.is_descriptor = require("kleros.tables.is_descriptor")
M.is_focus = require("kleros.tables.is_focus")
M.is_overland_landmark = require("kleros.tables.is_overland_landmark")
M.is_overland_waypoint = require("kleros.tables.is_overland_waypoint")
M.is_overland_peril = require("kleros.tables.is_overland_peril")
M.is_overland_opportunity = require("kleros.tables.is_overland_opportunity")
M.is_coastal_waters_landmark = require("kleros.tables.is_coastal_waters_landmark")
M.is_coastal_waters_waypoint = require("kleros.tables.is_coastal_waters_waypoint")
M.is_coastal_waters_peril = require("kleros.tables.is_coastal_waters_peril")
M.is_coastal_waters_opportunity = require("kleros.tables.is_coastal_waters_opportunity")
M.is_settlement_type = require("kleros.tables.is_settlement_type")
M.is_settlement_condition = require("kleros.tables.is_settlement_condition")
M.is_settlement_disposition = require("kleros.tables.is_settlement_disposition")
M.is_settlement_first_look = require("kleros.tables.is_settlement_first_look")
M.is_settlement_project = require("kleros.tables.is_settlement_project")
M.is_settlement_troubles = require("kleros.tables.is_settlement_troubles")
M.is_settlement_cultural_touchstones = require("kleros.tables.is_settlement_cultural_touchstones")

return M