local M = {}

M.is_settlement_first_look = {
	name = "Ironsworn Settlement First Look",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "At a crossroads" },
		{ min = 3, max = 4, result = "Beacon or signal fire" },
		{ min = 5, max = 6, result = "Boundary of standing stones" },
		{ min = 7, max = 8, result = "Breached or collapsed wall" },
		{ min = 9, max = 10, result = "Built among ancient ruins" },
		{ min = 11, max = 12, result = "Built on a hill or crag" },
		{ min = 13, max = 14, result = "Built over or beside water" },
		{ min = 15, max = 16, result = "Carved animal motifs" },
		{ min = 17, max = 18, result = "Central tree" },
		{ min = 19, max = 20, result = "Building a prominent structure" },
		{ min = 21, max = 22, result = "Decorated for a festival" },
		{ min = 23, max = 24, result = "Dense smoke from worksites" },
		{ min = 25, max = 26, result = "Nearby encampment" },
		{ min = 27, max = 28, result = "Encroaching woodland" },
		{ min = 29, max = 30, result = "Expansive fields or agriculture" },
		{ min = 31, max = 32, result = "Large barrow mound" },
		{ min = 33, max = 34, result = "Filled with song and music" },
		{ min = 35, max = 36, result = "Flying a familiar banner" },
		{ min = 37, max = 38, result = "Hastily improvised defenses" },
		{ min = 39, max = 40, result = "Heavily armed guards" },
		{ min = 41, max = 42, result = "Hung with charms and wards" },
		{ min = 43, max = 44, result = "In the shadow of a terrain feature" },
		{ min = 45, max = 46, result = "Large communal building" },
		{ min = 47, max = 48, result = "Numerous grazing animals" },
		{ min = 49, max = 50, result = "Protected by stout walls" },
		{ min = 51, max = 52, result = "Ringed by a moat or ditch" },
		{ min = 53, max = 54, result = "Sections divided by walls" },
		{ min = 55, max = 56, result = "Watchtowers or lookouts" },
		{ min = 57, max = 57, result = "Adorned with colorful banners" },
		{ min = 58, max = 58, result = "Armed with heavy weapons" },
		{ min = 59, max = 59, result = "Built into the terrain" },
		{ min = 60, max = 60, result = "Burning pit or pyre" },
		{ min = 61, max = 61, result = "Circling carrion birds" },
		{ min = 62, max = 62, result = "Connected by bridges" },
		{ min = 63, max = 63, result = "Large monolith or tower" },
		{ min = 64, max = 64, result = "Large statue or effigy" },
		{ min = 65, max = 65, result = "Loud laughter or merrymaking" },
		{ min = 66, max = 66, result = "Marked with cryptic symbols" },
		{ min = 67, max = 67, result = "Numerous comings and goings" },
		{ min = 68, max = 68, result = "Oddly quiet" },
		{ min = 69, max = 69, result = "One building set apart" },
		{ min = 70, max = 70, result = "Partially abandoned" },
		{ min = 71, max = 71, result = "Prisoners or dead on display" },
		{ min = 72, max = 72, result = "Repairs underway" },
		{ min = 73, max = 73, result = "Scars of an attack or disaster" },
		{ min = 74, max = 74, result = "Shrouded by mist" },
		{ min = 75, max = 75, result = "Signs of sickness" },
		{ min = 76, max = 76, result = "Signs of an occupying force" },
		{ min = 77, max = 77, result = "Signs of unrest" },
		{ min = 78, max = 78, result = "Surrounded by fresh graves" },
		{ min = 79, max = 79, result = "Surrounded by lush terrain" },
		{ min = 80, max = 80, result = "Trophies of defeated foes" },
		{ min = 81, max = 81, result = "Lush gardens" },
		{ min = 82, max = 82, result = "Visited by large caravan or fleet" },
		{ min = 83, max = 83, result = "Widely dispersed structures" },
		{ min = 84, max = 84, result = "Alluring fragrances" },
		{ min = 85, max = 85, result = "Built from unusual materials" },
		{ min = 86, max = 86, result = "Busy marketplace" },
		{ min = 87, max = 87, result = "Festooned with bones and skulls" },
		{ min = 88, max = 88, result = "Flooded or waterlogged section" },
		{ min = 89, max = 89, result = "Foul stench" },
		{ min = 90, max = 90, result = "Partially destroyed by fire" },
		{ min = 91, max = 91, result = "Oddly-shaped structures" },
		{ min = 92, max = 92, result = "Old siege weapons left to rot" },
		{ min = 93, max = 93, result = "Signs of infestation or corruption" },
		{ min = 94, max = 94, result = "Solemn procession" },
		{ min = 95, max = 95, result = "Hung with countless torches" },
		{ min = 96, max = 96, result = "Eerie light or strange energies" },
		{ min = 97, max = 97, result = "Surrounded by blighted terrain" },
		{ min = 98, max = 98, result = "Unusual domesticated creatures" },
		{ min = 99, max = 99, result = "Eerie chanting or keening" },
		{ min = 100, max = 100, result = "Spectral manifestations" },
	},
}

return M