local M = {}

M.is_settlement_name_generator = {
	name = "Ironsworn Settlement Name Generator",
	type = "compound",
	dice = "1d100",
	elements = 2,
	entries = {
		{ element1 = "Lost-", element2 = "-grove" },
		{ element1 = "Forge-", element2 = "-break" },
		{ element1 = "Gloom-", element2 = "-haven" },
		{ element1 = "Fallow-", element2 = "-mire" },
		{ element1 = "Night-", element2 = "-bourne" },
		{ element1 = "Red-", element2 = "-brook" },
		{ element1 = "Stone-", element2 = "-bridge" },
		{ element1 = "Wyrd-", element2 = "-wick" },
		{ element1 = "Bright-", element2 = "-peak" },
		{ element1 = "Bleak-", element2 = "-harrow" },
		{ element1 = "Dusk-", element2 = "-shard" },
		{ element1 = "Wood-", element2 = "-hall" },
		{ element1 = "White-", element2 = "-glade" },
		{ element1 = "Gray-", element2 = "-watch" },
		{ element1 = "Grim-", element2 = "-hold" },
		{ element1 = "Draug-", element2 = "-well" },
		{ element1 = "Wrath-", element2 = "-stead" },
		{ element1 = "High-", element2 = "-gate" },
		{ element1 = "Sword-", element2 = "-crest" },
		{ element1 = "Raven-", element2 = "-mount" },
		{ element1 = "Wyrm-", element2 = "-rock" },
		{ element1 = "Deep-", element2 = "-ridge" },
		{ element1 = "Shield-", element2 = "-fall" },
		{ element1 = "Tide-", element2 = "-ward" },
		{ element1 = "Keld-", element2 = "-mark" },
		{ element1 = "Ash-", element2 = "-mere" },
		{ element1 = "Low-", element2 = "-fen" },
		{ element1 = "Frost-", element2 = "-field" },
		{ element1 = "Troll-", element2 = "-barrow" },
		{ element1 = "Dark-", element2 = "-river" },
		{ element1 = "New-", element2 = "-ford" },
		{ element1 = "Storm-", element2 = "-hill" },
		{ element1 = "Mead-", element2 = "-wood" },
		{ element1 = "Ember-", element2 = "-tarn" },
		{ element1 = "Drift-", element2 = "-run" },
		{ element1 = "Flint-", element2 = "-spire" },
		{ element1 = "Wolf-", element2 = "-croft" },
		{ element1 = "Thorn-", element2 = "-scar" },
		{ element1 = "Long-", element2 = "-knoll" },
		{ element1 = "Axe-", element2 = "-roost" },
		{ element1 = "Iron-", element2 = "-march" },
		{ element1 = "Black-", element2 = "-shade" },
		{ element1 = "Shale-", element2 = "-reach" },
		{ element1 = "Nettle-", element2 = "-stone" },
		{ element1 = "Woad-", element2 = "-bluff" },
		{ element1 = "Broad-", element2 = "-nest" },
		{ element1 = "Rock-", element2 = "-holt" },
		{ element1 = "Hearth-", element2 = "-pass" },
		{ element1 = "Murk-", element2 = "-home" },
		{ element1 = "Ice-", element2 = "-point" },
		{ element1 = "Moon-", element2 = "-hope" },
		{ element1 = "Bitter-", element2 = "-vault" },
		{ element1 = "Fire-", element2 = "-wark" },
		{ element1 = "Great-", element2 = "-cairn" },
		{ element1 = "Green-", element2 = "-burrow" },
		{ element1 = "Bear-", element2 = "-hollow" },
		{ element1 = "Gold-", element2 = "-glen" },
		{ element1 = "Skarn-", element2 = "-moor" },
		{ element1 = "Mourn-", element2 = "-mist" },
		{ element1 = "Shade-", element2 = "-crag" },
		{ element1 = "Wind-", element2 = "-break" },
		{ element1 = "Star-", element2 = "-mire" },
		{ element1 = "Sea-", element2 = "-bourne" },
		{ element1 = "Dun-", element2 = "-brook" },
		{ element1 = "Gold-", element2 = "-bridge" },
		{ element1 = "Silver-", element2 = "-wick" },
		{ element1 = "Cold-", element2 = "-peak" },
		{ element1 = "Warm-", element2 = "-harrow" },
		{ element1 = "Wild-", element2 = "-shard" },
		{ element1 = "Old-", element2 = "-hall" },
		{ element1 = "Elder-", element2 = "-glade" },
		{ element1 = "Young-", element2 = "-watch" },
		{ element1 = "Fair-", element2 = "-hold" },
		{ element1 = "Foul-", element2 = "-well" },
		{ element1 = "Harsh-", element2 = "-stead" },
		{ element1 = "Mild-", element2 = "-gate" },
		{ element1 = "Brave-", element2 = "-crest" },
		{ element1 = "Coward-", element2 = "-mount" },
		{ element1 = "Wise-", element2 = "-rock" },
		{ element1 = "Fool-", element2 = "-ridge" },
		{ element1 = "Swift-", element2 = "-fall" },
		{ element1 = "Slow-", element2 = "-ward" },
		{ element1 = "True-", element2 = "-mark" },
		{ element1 = "False-", element2 = "-mere" },
		{ element1 = "Pure-", element2 = "-fen" },
		{ element1 = "Corrupt-", element2 = "-field" },
		{ element1 = "Ancient-", element2 = "-barrow" },
		{ element1 = "New-", element2 = "-river" },
		{ element1 = " Forgotten-", element2 = "-ford" },
		{ element1 = " Sacred-", element2 = "-hill" },
		{ element1 = "Profane-", element2 = "-wood" },
		{ element1 = "Fallen-", element2 = "-tarn" },
		{ element1 = "Risen-", element2 = "-run" },
		{ element1 = "Silent-", element2 = "-croft" },
		{ element1 = "Loud-", element2 = "-scar" },
		{ element1 = "Still-", element2 = "-knoll" },
		{ element1 = "Moving-", element2 = "-roost" },
		{ element1 = "Fixed-", element2 = "-march" },
		{ element1 = "Broken-", element2 = "-shade" },
		{ element1 = "Whole-", element2 = "-reach" },
	},
}

return M