local M = {}

M.is_settlement_project = {
	name = "Ironsworn Settlement Project",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 4, result = "Farming" },
		{ min = 5, max = 7, result = "Celebration" },
		{ min = 8, max = 10, result = "Conquest" },
		{ min = 11, max = 14, result = "Religion" },
		{ min = 15, max = 16, result = "Secrecy" },
		{ min = 17, max = 18, result = "Debauchery" },
		{ min = 19, max = 21, result = "Construction" },
		{ min = 22, max = 23, result = "Evacuation" },
		{ min = 24, max = 25, result = "Diplomacy" },
		{ min = 26, max = 29, result = "Mysticism" },
		{ min = 30, max = 31, result = "History" },
		{ min = 32, max = 33, result = "Beast hunting" },
		{ min = 34, max = 35, result = "Scavenging" },
		{ min = 36, max = 39, result = "Brewing" },
		{ min = 40, max = 43, result = "Defense" },
		{ min = 44, max = 46, result = "Exploration" },
		{ min = 47, max = 48, result = "Patrolling" },
		{ min = 49, max = 52, result = "Mining" },
		{ min = 53, max = 54, result = "Entertainment" },
		{ min = 55, max = 58, result = "Herding" },
		{ min = 59, max = 62, result = "Foraging" },
		{ min = 63, max = 66, result = "Trade" },
		{ min = 67, max = 70, result = "Forestry" },
		{ min = 71, max = 74, result = "Healing" },
		{ min = 75, max = 78, result = "Hunting or fishing" },
		{ min = 79, max = 81, result = "Hospitality" },
		{ min = 82, max = 85, result = "Craftwork" },
		{ min = 86, max = 89, result = "Smithing" },
		{ min = 90, max = 92, result = "Raiding" },
		{ min = 93, max = 94, result = "Treasure hunting" },
		{ min = 95, max = 96, result = "Taming" },
		{ min = 97, max = 98, result = "Preservation" },
		{ min = 99, max = 100, result = "Education" },
	},
}

return M