local M = {}

M.isCharacterGoal = {
	name = "Ironsworn Character Goal",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 3, result = "Obtain an object" },
		{ min = 4, max = 6, result = "Make an agreement" },
		{ min = 7, max = 9, result = "Build a relationship" },
		{ min = 10, max = 12, result = "Undermine a relationship" },
		{ min = 13, max = 15, result = "Seek a truth" },
		{ min = 16, max = 18, result = "Pay a debt" },
		{ min = 19, max = 21, result = "Refute a falsehood" },
		{ min = 22, max = 24, result = "Harm a rival" },
		{ min = 25, max = 27, result = "Cure an ill" },
		{ min = 28, max = 30, result = "Find a person" },
		{ min = 31, max = 33, result = "Find a home" },
		{ min = 34, max = 36, result = "Seize power" },
		{ min = 37, max = 39, result = "Restore a relationship" },
		{ min = 40, max = 42, result = "Create an item" },
		{ min = 43, max = 45, result = "Travel to a place" },
		{ min = 46, max = 48, result = "Secure provisions" },
		{ min = 49, max = 51, result = "Rebel against power" },
		{ min = 52, max = 54, result = "Collect a debt" },
		{ min = 55, max = 57, result = "Protect a secret" },
		{ min = 58, max = 60, result = "Spread faith" },
		{ min = 61, max = 63, result = "Enrich themselves" },
		{ min = 64, max = 66, result = "Protect a person" },
		{ min = 67, max = 69, result = "Protect the status quo" },
		{ min = 70, max = 72, result = "Advance status" },
		{ min = 73, max = 75, result = "Defend a place" },
		{ min = 76, max = 78, result = "Avenge a wrong" },
		{ min = 79, max = 81, result = "Fulfill a duty" },
		{ min = 82, max = 84, result = "Gain knowledge" },
		{ min = 85, max = 87, result = "Prove worthiness" },
		{ min = 88, max = 90, result = "Find redemption" },
		{ min = 91, max = 92, result = "Escape from something" },
		{ min = 93, max = 95, result = "Resolve a dispute" },
		{ min = 96, max = 100, result = "Roll twice" },
	},
}

return M