local M = {}

M.isCharacterFirstLook = {
	name = "Ironsworn Character First Look",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Well-armed" },
		{ min = 3, max = 4, result = "Alluring" },
		{ min = 5, max = 6, result = "Mystical" },
		{ min = 7, max = 8, result = "Pursued" },
		{ min = 9, max = 10, result = "Beastly" },
		{ min = 11, max = 12, result = "Stout" },
		{ min = 13, max = 14, result = "Confused" },
		{ min = 15, max = 16, result = "Equiped" },
		{ min = 17, max = 18, result = "Distressed" },
		{ min = 19, max = 20, result = "Fearsome" },
		{ min = 21, max = 22, result = "Cloaked" },
		{ min = 23, max = 24, result = "Guarded" },
		{ min = 25, max = 26, result = "Commanding" },
		{ min = 27, max = 28, result = "Weathered" },
		{ min = 29, max = 30, result = "Unassuming" },
		{ min = 31, max = 32, result = "Attractive" },
		{ min = 33, max = 34, result = "Youthful" },
		{ min = 35, max = 36, result = "Armored" },
		{ min = 37, max = 38, result = "Drunk" },
		{ min = 39, max = 40, result = "Silent" },
		{ min = 41, max = 42, result = "Brutish" },
		{ min = 43, max = 44, result = "Ghostly" },
		{ min = 45, max = 46, result = "Sickly" },
		{ min = 47, max = 48, result = "Accented" },
		{ min = 49, max = 50, result = "Poised" },
		{ min = 51, max = 52, result = "Well-mannered" },
		{ min = 53, max = 54, result = "Menacing" },
		{ min = 55, max = 56, result = "Filthy" },
		{ min = 57, max = 58, result = "Wounded" },
		{ min = 59, max = 60, result = "Mysterious" },
		{ min = 61, max = 62, result = "Imposing" },
		{ min = 63, max = 64, result = "Ill-equipped" },
		{ min = 65, max = 66, result = "Scarred" },
		{ min = 67, max = 68, result = "Slight" },
		{ min = 69, max = 70, result = "Tattooed" },
		{ min = 71, max = 72, result = "Grim" },
		{ min = 73, max = 74, result = "Masked" },
		{ min = 75, max = 76, result = "Distinguished" },
		{ min = 77, max = 78, result = "Fit" },
		{ min = 79, max = 80, result = "Firstborn" },
		{ min = 81, max = 82, result = "Bloodstained" },
		{ min = 83, max = 84, result = "Overburdened" },
		{ min = 85, max = 86, result = "Furtive" },
		{ min = 87, max = 88, result = "Aged" },
		{ min = 89, max = 90, result = "Graceful" },
		{ min = 91, max = 92, result = "Inhuman" },
		{ min = 93, max = 94, result = "Sinister" },
		{ min = 95, max = 96, result = "Visibly disabled" },
		{ min = 97, max = 98, result = "Concealed" },
		{ min = 99, max = 100, result = "Uncanny" },
	},
}

return M
