local M = {}

M.isDelveSiteNamePlace = {
	name = "Ironsworn Delve Site Name Place",
	type = "select",
	dice = "1d100",
	entries = {
		barrow = {
			name = "Barrow",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Barrow" },
				{ min = 11, max = 20, result = "Boneyard" },
				{ min = 21, max = 30, result = "Chambers" },
				{ min = 31, max = 40, result = "Charnel" },
				{ min = 41, max = 50, result = "Crypt" },
				{ min = 51, max = 60, result = "Grave" },
				{ min = 61, max = 70, result = "Mound" },
				{ min = 71, max = 80, result = "Pit" },
				{ min = 81, max = 90, result = "Sepulcher" },
				{ min = 91, max = 100, result = "Tomb" },
			},
		},
		cavern = {
			name = "Cavern",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Abyss" },
				{ min = 11, max = 20, result = "Cavern" },
				{ min = 21, max = 30, result = "Caves" },
				{ min = 31, max = 40, result = "Chasm" },
				{ min = 41, max = 50, result = "Depths" },
				{ min = 51, max = 60, result = "Hollow" },
				{ min = 61, max = 70, result = "Lair" },
				{ min = 71, max = 80, result = "Rift" },
				{ min = 81, max = 90, result = "Tunnels" },
				{ min = 91, max = 100, result = "Warren" },
			},
		},
		frozencavern = {
			name = "Frozen Cavern",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Break" },
				{ min = 11, max = 20, result = "Brumal" },
				{ min = 21, max = 30, result = "Cavern" },
				{ min = 31, max = 40, result = "Chasm" },
				{ min = 41, max = 50, result = "Crevasse" },
				{ min = 51, max = 60, result = "Depths" },
				{ min = 61, max = 70, result = "Fissure" },
				{ min = 71, max = 80, result = "Lair" },
				{ min = 81, max = 90, result = "Moulin" },
				{ min = 91, max = 100, result = "Rimevault" },
			},
		},
		icereach = {
			name = "Icereach",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Drift" },
				{ min = 11, max = 20, result = "Expanse" },
				{ min = 21, max = 30, result = "Floe" },
				{ min = 31, max = 40, result = "Icemark" },
				{ min = 41, max = 50, result = "Icemere" },
				{ min = 51, max = 60, result = "Reach" },
				{ min = 61, max = 70, result = "Rimefield" },
				{ min = 71, max = 80, result = "Thule" },
				{ min = 81, max = 90, result = "Waste" },
				{ min = 91, max = 100, result = "Wintertide" },
			},
		},
		mine = {
			name = "Mine",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Bore" },
				{ min = 11, max = 20, result = "Cut" },
				{ min = 21, max = 30, result = "Dig" },
				{ min = 31, max = 40, result = "Forge" },
				{ min = 41, max = 50, result = "Gouge" },
				{ min = 51, max = 60, result = "Hoard" },
				{ min = 61, max = 70, result = "Lode" },
				{ min = 71, max = 80, result = "Mine" },
				{ min = 81, max = 90, result = "Pit" },
				{ min = 91, max = 100, result = "Works" },
			},
		},
		pass = {
			name = "Pass",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Cliffs" },
				{ min = 11, max = 20, result = "Crag" },
				{ min = 21, max = 30, result = "Cut" },
				{ min = 31, max = 40, result = "Gap" },
				{ min = 41, max = 50, result = "Gorge" },
				{ min = 51, max = 60, result = "Heights" },
				{ min = 61, max = 70, result = "Highlands" },
				{ min = 71, max = 80, result = "Pass" },
				{ min = 81, max = 90, result = "Reach" },
				{ min = 91, max = 100, result = "Ridge" },
			},
		},
		ruin = {
			name = "Ruin",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Citadel" },
				{ min = 11, max = 20, result = "Enclave" },
				{ min = 21, max = 30, result = "Fortress" },
				{ min = 31, max = 40, result = "Hall" },
				{ min = 41, max = 50, result = "Keep" },
				{ min = 51, max = 60, result = "Sanctuary" },
				{ min = 61, max = 70, result = "Sanctum" },
				{ min = 71, max = 80, result = "Spire" },
				{ min = 81, max = 90, result = "Temple" },
				{ min = 91, max = 100, result = "Tower" },
			},
		},
		seacave = {
			name = "Sea Cave",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Caves" },
				{ min = 11, max = 20, result = "Channel" },
				{ min = 21, max = 30, result = "Cove" },
				{ min = 31, max = 40, result = "Depths" },
				{ min = 41, max = 50, result = "Hollow" },
				{ min = 51, max = 60, result = "Lair" },
				{ min = 61, max = 70, result = "Pools" },
				{ min = 71, max = 80, result = "Tides" },
				{ min = 81, max = 90, result = "Trough" },
				{ min = 91, max = 100, result = "Waters" },
			},
		},
		shadowfen = {
			name = "Shadowfen",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Bog" },
				{ min = 11, max = 20, result = "Fen" },
				{ min = 21, max = 30, result = "Floodlands" },
				{ min = 31, max = 40, result = "Lowland" },
				{ min = 41, max = 50, result = "Marsh" },
				{ min = 51, max = 60, result = "Mire" },
				{ min = 61, max = 70, result = "Morass" },
				{ min = 71, max = 80, result = "Quagmire" },
				{ min = 81, max = 90, result = "Slough" },
				{ min = 91, max = 100, result = "Wetlands" },
			},
		},
		stronghold = {
			name = "Stronghold",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Bastion" },
				{ min = 11, max = 20, result = "Citadel" },
				{ min = 21, max = 30, result = "Fortress" },
				{ min = 31, max = 40, result = "Garrison" },
				{ min = 41, max = 50, result = "Haven" },
				{ min = 51, max = 60, result = "Keep" },
				{ min = 61, max = 70, result = "Outpost" },
				{ min = 71, max = 80, result = "Refuge" },
				{ min = 81, max = 90, result = "Sanctuary" },
				{ min = 91, max = 100, result = "Watch" },
			},
		},
		tanglewood = {
			name = "Tanglewood",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Bramble" },
				{ min = 11, max = 20, result = "Briar" },
				{ min = 21, max = 30, result = "Forest" },
				{ min = 31, max = 40, result = "Grove" },
				{ min = 41, max = 50, result = "Silva" },
				{ min = 51, max = 60, result = "Tangle" },
				{ min = 61, max = 70, result = "Thicket" },
				{ min = 71, max = 80, result = "Weald" },
				{ min = 81, max = 90, result = "Wilds" },
				{ min = 91, max = 100, result = "Wood" },
			},
		},
		underkeep = {
			name = "Underkeep",
			type = "range",
			dice = "1d100",
			entries = {
				{ min = 1, max = 10, result = "Catacomb" },
				{ min = 11, max = 20, result = "Chambers" },
				{ min = 21, max = 30, result = "Den" },
				{ min = 31, max = 40, result = "Hall" },
				{ min = 41, max = 50, result = "Labyrinth" },
				{ min = 51, max = 60, result = "Maze" },
				{ min = 61, max = 70, result = "Pit" },
				{ min = 71, max = 80, result = "Sanctum" },
				{ min = 81, max = 90, result = "Underkeep" },
				{ min = 91, max = 100, result = "Vault" },
			},
		},
	},
	place_types = {
		{ min = 1, max = 6, result = "Barrow", key = "barrow" },
		{ min = 7, max = 18, result = "Cavern", key = "cavern" },
		{ min = 19, max = 28, result = "Frozen Cavern", key = "frozencavern" },
		{ min = 29, max = 32, result = "Icereach", key = "icereach" },
		{ min = 33, max = 38, result = "Mine", key = "mine" },
		{ min = 39, max = 48, result = "Pass", key = "pass" },
		{ min = 49, max = 58, result = "Ruin", key = "ruin" },
		{ min = 59, max = 68, result = "Sea Cave", key = "seacave" },
		{ min = 69, max = 78, result = "Shadowfen", key = "shadowfen" },
		{ min = 79, max = 83, result = "Stronghold", key = "stronghold" },
		{ min = 84, max = 95, result = "Tanglewood", key = "tanglewood" },
		{ min = 96, max = 100, result = "Underkeep", key = "underkeep" },
	},
}

return M