local M = {}

M.isDelveSiteNameNamesake = {
	name = "Ironsworn Delve Site Name Namesake",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Breckon" },
		{ min = 3, max = 4, result = "Issara" },
		{ min = 5, max = 6, result = "Milenna" },
		{ min = 7, max = 8, result = "Thorval" },
		{ min = 9, max = 10, result = "Khulan" },
		{ min = 11, max = 12, result = "Aurvang" },
		{ min = 13, max = 14, result = "Kalida" },
		{ min = 15, max = 16, result = "Keeara" },
		{ min = 17, max = 18, result = "Andor" },
		{ min = 19, max = 20, result = "Zakaria" },
		{ min = 21, max = 22, result = "Willa" },
		{ min = 23, max = 24, result = "Etana" },
		{ min = 25, max = 26, result = "Valgard" },
		{ min = 27, max = 28, result = "Kenrick" },
		{ min = 29, max = 30, result = "Wyland" },
		{ min = 31, max = 32, result = "Sidura" },
		{ min = 33, max = 34, result = "Svala" },
		{ min = 35, max = 36, result = "Kajir" },
		{ min = 37, max = 38, result = "Saiven" },
		{ min = 39, max = 40, result = "Callwen" },
		{ min = 41, max = 42, result = "Zhan" },
		{ min = 43, max = 44, result = "Solana" },
		{ min = 45, max = 46, result = "Ildar" },
		{ min = 47, max = 48, result = "Keelan" },
		{ min = 49, max = 50, result = "Thrain" },
		{ min = 51, max = 52, result = "Kynan" },
		{ min = 53, max = 54, result = "Jadina" },
		{ min = 55, max = 56, result = "Radek" },
		{ min = 57, max = 58, result = "Wulan" },
		{ min = 59, max = 60, result = "Garion" },
		{ min = 61, max = 62, result = "Eysa" },
		{ min = 63, max = 64, result = "Kolor" },
		{ min = 65, max = 66, result = "Katarra" },
		{ min = 67, max = 68, result = "Dain" },
		{ min = 69, max = 70, result = "Farina" },
		{ min = 71, max = 72, result = "Yala" },
		{ min = 73, max = 74, result = "Kodroth" },
		{ min = 75, max = 76, result = "Morien" },
		{ min = 77, max = 78, result = "Akida" },
		{ min = 79, max = 80, result = "Haldorr" },
		{ min = 81, max = 82, result = "Nyrad" },
		{ min = 83, max = 84, result = "Edda" },
		{ min = 85, max = 86, result = "Jorund" },
		{ min = 87, max = 88, result = "Morraine" },
		{ min = 89, max = 90, result = "Lindar" },
		{ min = 91, max = 92, result = "Sithra" },
		{ min = 93, max = 94, result = "Torgan" },
		{ min = 95, max = 96, result = "Arnorr" },
		{ min = 97, max = 98, result = "Thyri" },
		{ min = 99, max = 100, result = "Erisia" },
	},
}

return M