local M = {}

M.isDelveSiteNameDescription = {
	name = "Ironsworn Delve Site Name Description",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Deep" },
		{ min = 3, max = 4, result = "Tainted" },
		{ min = 5, max = 6, result = "Grey" },
		{ min = 7, max = 8, result = "Forgotten" },
		{ min = 9, max = 10, result = "Flooded" },
		{ min = 11, max = 12, result = "Forbidden" },
		{ min = 13, max = 14, result = "Barren" },
		{ min = 15, max = 16, result = "Lost" },
		{ min = 17, max = 18, result = "Cursed" },
		{ min = 19, max = 20, result = "Fell" },
		{ min = 21, max = 22, result = "Sunken" },
		{ min = 23, max = 24, result = "Nightmare" },
		{ min = 25, max = 26, result = "Infernal" },
		{ min = 27, max = 28, result = "Dark" },
		{ min = 29, max = 30, result = "Bloodstained" },
		{ min = 31, max = 32, result = "Haunted" },
		{ min = 33, max = 34, result = "White" },
		{ min = 35, max = 36, result = "Shrouded" },
		{ min = 37, max = 38, result = "Wasted" },
		{ min = 39, max = 40, result = "Grim" },
		{ min = 41, max = 42, result = "Endless" },
		{ min = 43, max = 44, result = "Crumbling" },
		{ min = 45, max = 46, result = "Undying" },
		{ min = 47, max = 48, result = "Bloodied" },
		{ min = 49, max = 50, result = "Forsaken" },
		{ min = 51, max = 52, result = "Silent" },
		{ min = 53, max = 54, result = "Blighted" },
		{ min = 55, max = 56, result = "Iron" },
		{ min = 57, max = 58, result = "Frozen" },
		{ min = 59, max = 60, result = "Abyssal" },
		{ min = 61, max = 62, result = "Crimson" },
		{ min = 63, max = 64, result = "Silver" },
		{ min = 65, max = 66, result = "Desecrated" },
		{ min = 67, max = 68, result = "Ashen" },
		{ min = 69, max = 70, result = "Elder" },
		{ min = 71, max = 72, result = "Scorched" },
		{ min = 73, max = 74, result = "Unknown" },
		{ min = 75, max = 76, result = "Scarred" },
		{ min = 77, max = 78, result = "Broken" },
		{ min = 79, max = 80, result = "Chaotic" },
		{ min = 81, max = 82, result = "Black" },
		{ min = 83, max = 84, result = "Hidden" },
		{ min = 85, max = 86, result = "Sundered" },
		{ min = 87, max = 88, result = "Shattered" },
		{ min = 89, max = 90, result = "Dreaded" },
		{ min = 91, max = 92, result = "Secret" },
		{ min = 93, max = 94, result = "High" },
		{ min = 95, max = 96, result = "Sacred" },
		{ min = 97, max = 98, result = "Fallen" },
		{ min = 99, max = 100, result = "Ruined" },
	},
}

return M