local M = {}

M.isDelveSiteNameDetail = {
	name = "Ironsworn Delve Site Name Detail",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Blight" },
		{ min = 3, max = 4, result = "Strife" },
		{ min = 5, max = 6, result = "Nightfall" },
		{ min = 7, max = 8, result = "Fury" },
		{ min = 9, max = 10, result = "Terror" },
		{ min = 11, max = 12, result = "Truth" },
		{ min = 13, max = 14, result = "Spring" },
		{ min = 15, max = 16, result = "Sanctuary" },
		{ min = 17, max = 18, result = "Bone" },
		{ min = 19, max = 20, result = "Specters" },
		{ min = 21, max = 22, result = "Daybreak" },
		{ min = 23, max = 24, result = "Doom" },
		{ min = 25, max = 26, result = "Treachery" },
		{ min = 27, max = 28, result = "Blood" },
		{ min = 29, max = 30, result = "War" },
		{ min = 31, max = 32, result = "Torment" },
		{ min = 33, max = 34, result = "Iron" },
		{ min = 35, max = 36, result = "Silence" },
		{ min = 37, max = 38, result = "Mist" },
		{ min = 39, max = 40, result = "Isolation" },
		{ min = 41, max = 42, result = "Runes" },
		{ min = 43, max = 44, result = "Rot" },
		{ min = 45, max = 46, result = "Corruption" },
		{ min = 47, max = 48, result = "Prophecy" },
		{ min = 49, max = 50, result = "Fate" },
		{ min = 51, max = 52, result = "Twilight" },
		{ min = 53, max = 54, result = "Power" },
		{ min = 55, max = 56, result = "Darkness" },
		{ min = 57, max = 58, result = "Gloom" },
		{ min = 59, max = 60, result = "Storms" },
		{ min = 61, max = 62, result = "Hope" },
		{ min = 63, max = 64, result = "Lament" },
		{ min = 65, max = 66, result = "Frost" },
		{ min = 67, max = 68, result = "Souls" },
		{ min = 69, max = 70, result = "Winter" },
		{ min = 71, max = 72, result = "Sadness" },
		{ min = 73, max = 74, result = "Desolation" },
		{ min = 75, max = 76, result = "Bane" },
		{ min = 77, max = 78, result = "Lies" },
		{ min = 79, max = 80, result = "Ash" },
		{ min = 81, max = 82, result = "Banishment" },
		{ min = 83, max = 84, result = "Shadow" },
		{ min = 85, max = 86, result = "Madness" },
		{ min = 87, max = 88, result = "Stone" },
		{ min = 89, max = 90, result = "Secrets" },
		{ min = 91, max = 92, result = "Despair" },
		{ min = 93, max = 94, result = "Blades" },
		{ min = 95, max = 96, result = "Dread" },
		{ min = 97, max = 98, result = "Light" },
		{ min = 99, max = 100, result = "Wrath" },
	},
}

return M