local M = {}

M.isOverlandWaypoint = {
    name = "Ironsworn Overland Waypoint",
    type = "simple",
    dice = "1d100",
    entries = {
        "A camp or settlement comes into view",
        "A long-dead corpse or skeleton lies here",
        "A herd of wildlife cuts across your path",
        "A wide river winds across the landscape",
        "Flies swarm around an enormous pile of scat",
        "A stone wall marks an old boundary line",
        "A cold fire pit hints at the passage of another traveler",
        "An unsettling silence falls over this area",
        "You discover the remnants of a ritual",
        "A crude wall or barricade marks a makeshift fortification",
        "You cross paths with a lone traveler",
        "Ash surrounds a long-cold funeral pyre",
        "A creature stands in defense of its nest or young",
        "Trinkets and offerings hang from a tree or monument",
        "A stone-framed doorway marks the entrance to a barrow mound",
        "Tracks show that others have passed this way",
        "You catch a gleam of metal in the distance",
        "A waterway cuts through the landscape",
        "A ford or ferry marks a river crossing",
        "You encounter a procession of refugees or nomads",
        "A grim marker denotes a territorial boundary",
        "A former worksite lies abandoned",
        "You hear the footfalls or stirrings of a large creature",
        "Something about this place evokes an unnerving sensation",
        "An abandoned or lifeless settlement lingers in silence",
        "The temperature shifts unnaturally",
        "A storm brews on the horizon",
        "A lake, pond, or pool reflects its surroundings",
        "This place gives you the discomforting feeling that you are being watched",
        "A rope bridge sways in the wind",
        "A broken bridge marks a now-unused crossing",
        "A series of ramshackle bridges connect high places",
        "Phantom voices or song carry on the wind",
        "A constructed bridge spans a river or gap",
        "Something about this place spurs a memory",
        "You encounter a small group of travelers",
        "You discover the aftermath of a fight or battle",
        "A recent landslide, collapse, or rockfall scars the landscape",
        "Just ahead, a column of smoke rises into the sky",
        "A cave opening is carved into the side of a hill or cliff",
        "Several gravesites are here, each marked by an earthen or stone mound",
        "An overlook offers an expansive view of the landscape ahead",
        "Nature flourishes here",
        "Abandoned construction is all that remains of a failed project",
        "Ancient ruins stand here",
        "A great tree or rocky spire stands tall above its surroundings",
        "Carrion birds circle overheard—a bad omen",
        "You spot the banners of an armed force on the move",
        "Mist rises from a plunging waterfall",
        "You find disturbing remains or evidence of a violent death",
        "A natural bridge spans a river or gap",
        "Mystic stones or strange pillars stand here",
        "The landscape is strewn with a maze of rocky spires",
        "Fallen trees or upturned earth mark a destructive path",
        "Cleared, cultivated, or barren ground stands apart from its surroundings",
        "The nature of the landscape or environment changes",
        "Ghostlights dance above the landscape",
        "Scorched ground marks the location of a recent fire",
        "Steam rises from bubbling pools",
        "Stones or markings form a mystic circle",
        "Creatures gather at a source of water",
        "The path ascends a hill or ridgeline",
        "Carved symbols or likenesses adorn the landscape",
        "A great flying creature circles overhead",
        "A road or trail marks a well-used path",
        "The weather shifts, a portent of things to come",
        "The skeleton of a massive animal or beast lies here",
        "A large stone bears an inscription or message",
        "A ragged banner hangs from a leaning pole",
        "A makeshift shelter or solitary home lies abandoned",
        "A large creature hunts or forages here, but pays you no heed",
        "Carrion animals pick at scattered remains",
        "You hear the sounds of a nearby battle",
        "You hear the calls of unusual wildlife",
        "A spectral manifestation appears",
        "Natural or carved steps lead up a slope or cliffside",
        "An altar, shrine, or memorial marks a hallowed place",
        "The landscape is divided by a ravine or fissure",
        "A natural oasis stands amid an otherwise ruined or barren landscape",
        "A dry riverbed or trench cuts through the landscape like a scar",
        "Nature is stunted or diseased in this place",
        "An ancient monument or statue stands here",
        "A shadowy path leads along a narrow canyon or pass",
        "Tracks or claw marks reveal the passage of a large animal or beast",
        "A caravan is camped here or passing through",
        "Laborers toil at a worksite",
        "A signal station, lookout, or tower sits on high ground",
        "Scattered stones mark a toppled structure or monument",
        "A lingering fog clings to the terrain",
        "You top a rise, and catch sight of a trailing person or creature",
        "Intricately stacked cairn stones mark a lonely gravesite or remembrance",
        "A promontory or summit rises above the landscape",
        "A wagon or cart sits abandoned",
        "A crudely-fashioned effigy watches over the surroundings",
        "A sinkhole or pit leads to unseen depths",
        "An unusual tree or rock formation stands apart from its surroundings",
        "The path descends into a valley or basin",
        "The ground is scattered with broken bones",
        "The plants here are strangely at odds with their environment",
        "Blood-spattered ground or a bloody trail mark a violent end",
    }
}

return M