local M = {}

M.isSettlementCulturalTouchstones = {
	name = "Ironsworn Settlement Cultural Touchstones",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Austere styles" },
		{ min = 3, max = 4, result = "Prophecy" },
		{ min = 5, max = 6, result = "Rites of adulthood" },
		{ min = 7, max = 8, result = "Feasting and merrymaking" },
		{ min = 9, max = 10, result = "Gambling" },
		{ min = 11, max = 12, result = "Code of pacifism" },
		{ min = 13, max = 14, result = "Suspicion of outsiders" },
		{ min = 15, max = 16, result = "Formal duels" },
		{ min = 17, max = 18, result = "Mysticism" },
		{ min = 19, max = 20, result = "Adherence to authority" },
		{ min = 21, max = 22, result = "Song and dance" },
		{ min = 23, max = 24, result = "Uncommon languages" },
		{ min = 25, max = 26, result = "Heavily-accented speech" },
		{ min = 27, max = 28, result = "Artistic expression" },
		{ min = 29, max = 30, result = "Distinctive armor" },
		{ min = 31, max = 32, result = "Bartering" },
		{ min = 33, max = 34, result = "Long mourning periods" },
		{ min = 35, max = 36, result = "Seasonal festivals" },
		{ min = 37, max = 38, result = "Blood feuds" },
		{ min = 39, max = 40, result = "Banishment of the disloyal" },
		{ min = 41, max = 42, result = "Rigid hierarchy" },
		{ min = 43, max = 44, result = "Unbreakable vows" },
		{ min = 45, max = 46, result = "Communal resources" },
		{ min = 47, max = 48, result = "Spirituality" },
		{ min = 49, max = 50, result = "Strict laws" },
		{ min = 51, max = 52, result = "Respect of elders" },
		{ min = 53, max = 54, result = "Courtesy and hospitality" },
		{ min = 55, max = 56, result = "Body modifications or tattoos" },
		{ min = 57, max = 58, result = "Pilgrimages" },
		{ min = 59, max = 60, result = "Superstition" },
		{ min = 61, max = 62, result = "Ceremonies and rituals" },
		{ min = 63, max = 64, result = "Blood debts" },
		{ min = 65, max = 66, result = "Familial clans" },
		{ min = 67, max = 68, result = "Isolationism and privacy" },
		{ min = 69, max = 70, result = "Communal hunts" },
		{ min = 71, max = 72, result = "Competitive tournaments" },
		{ min = 73, max = 74, result = "Code of honor" },
		{ min = 75, max = 76, result = "Storytelling" },
		{ min = 77, max = 78, result = "Conquest and battle prowess" },
		{ min = 79, max = 80, result = "Martyred heroes" },
		{ min = 81, max = 82, result = "Sacred texts" },
		{ min = 83, max = 84, result = "Rites of courtship" },
		{ min = 85, max = 86, result = "Bonded creatures" },
		{ min = 87, max = 88, result = "Signature weapon" },
		{ min = 89, max = 90, result = "Hidden identities" },
		{ min = 91, max = 92, result = "Gift-giving" },
		{ min = 93, max = 94, result = "Animal or nature motifs" },
		{ min = 95, max = 96, result = "Independence from authority" },
		{ min = 97, max = 98, result = "Unusual death rites" },
		{ min = 99, max = 100, result = "Elaborate styles" },
	},
}

return M