local M = {}

M.isSettlementTroubles = {
	name = "Ironsworn Settlement Troubles",
	type = "range",
	dice = "1d100",
	entries = {
		{ min = 1, max = 2, result = "Outsiders rejected" },
		{ min = 3, max = 4, result = "Dangerous discovery" },
		{ min = 5, max = 6, result = "Dreadful omens" },
		{ min = 7, max = 8, result = "Natural disaster" },
		{ min = 9, max = 10, result = "Old wounds reopened" },
		{ min = 11, max = 12, result = "Important object is lost" },
		{ min = 13, max = 14, result = "Someone is captured" },
		{ min = 15, max = 16, result = "Mysterious phenomenon" },
		{ min = 17, max = 18, result = "Revolt against a leader" },
		{ min = 19, max = 20, result = "Vengeful outcast" },
		{ min = 21, max = 22, result = "Rival settlement" },
		{ min = 23, max = 24, result = "Nature strikes back" },
		{ min = 25, max = 26, result = "Someone is missing" },
		{ min = 27, max = 28, result = "Production halts" },
		{ min = 29, max = 30, result = "Mysterious murders" },
		{ min = 31, max = 32, result = "Debt comes due" },
		{ min = 33, max = 34, result = "Unjust leadership" },
		{ min = 35, max = 36, result = "Disastrous accident" },
		{ min = 37, max = 38, result = "In league with the enemy" },
		{ min = 39, max = 40, result = "Raiders prey on the weak" },
		{ min = 41, max = 42, result = "Cursed past" },
		{ min = 43, max = 44, result = "An innocent is accused" },
		{ min = 45, max = 46, result = "Corrupted by dark magic" },
		{ min = 47, max = 48, result = "Isolated by brutal weather" },
		{ min = 49, max = 50, result = "Provisions are scarce" },
		{ min = 51, max = 52, result = "Sickness run amok" },
		{ min = 53, max = 54, result = "Allies become enemies" },
		{ min = 55, max = 56, result = "Attack is imminent" },
		{ min = 57, max = 58, result = "Lost caravan" },
		{ min = 59, max = 60, result = "Dark secret revealed" },
		{ min = 61, max = 62, result = "Urgent expedition" },
		{ min = 63, max = 64, result = "A leader falls" },
		{ min = 65, max = 66, result = "Families in conflict" },
		{ min = 67, max = 68, result = "Incompetent leadership" },
		{ min = 69, max = 70, result = "Reckless warmongering" },
		{ min = 71, max = 72, result = "Beast on the hunt" },
		{ min = 73, max = 74, result = "Betrayed from within" },
		{ min = 75, max = 76, result = "Broken truce" },
		{ min = 77, max = 78, result = "Wrathful haunt" },
		{ min = 79, max = 80, result = "Conflict with firstborn" },
		{ min = 81, max = 82, result = "Trade route blocked" },
		{ min = 83, max = 84, result = "Caught in the crossfire" },
		{ min = 85, max = 86, result = "Stranger causes discord" },
		{ min = 87, max = 88, result = "Important event threatened" },
		{ min = 89, max = 90, result = "Dangerous tradition" },
		{ min = 91, max = 100, result = "Roll twice" },
	},
}

return M