local M = {}

M.overland_landmark = {
    name = "Overland Landmark",
    type = "range",
    dice = "1d100",
    entries = {
        { min = 1, max = 2, result = "Ruins" },
        { min = 3, max = 4, result = "Wall" },
        { min = 5, max = 6, result = "Battlefield" },
        { min = 7, max = 8, result = "Hovel" },
        { min = 9, max = 10, result = "Springs" },
        { min = 11, max = 12, result = "Campsite" },
        { min = 13, max = 14, result = "Bridge" },
        { min = 15, max = 16, result = "Barrow" },
        { min = 17, max = 18, result = "Gravesite" },
        { min = 19, max = 20, result = "Waterfall" },
        { min = 21, max = 22, result = "Cave" },
        { min = 23, max = 24, result = "Swamp" },
        { min = 25, max = 26, result = "Road" },
        { min = 27, max = 28, result = "Tree" },
        { min = 29, max = 30, result = "Pond" },
        { min = 31, max = 32, result = "Field" },
        { min = 33, max = 34, result = "Marsh" },
        { min = 35, max = 37, result = "Settlement" },
        { min = 38, max = 39, result = "Rapids" },
        { min = 40, max = 41, result = "Pass" },
        { min = 42, max = 43, result = "Trail" },
        { min = 44, max = 45, result = "Ridge" },
        { min = 46, max = 47, result = "Cliff" },
        { min = 48, max = 49, result = "Grove" },
        { min = 50, max = 51, result = "Moor" },
        { min = 52, max = 53, result = "Thicket" },
        { min = 54, max = 55, result = "River ford" },
        { min = 56, max = 57, result = "Valley" },
        { min = 58, max = 59, result = "Fjord / Ravine" },
        { min = 60, max = 61, result = "Foothills" },
        { min = 62, max = 63, result = "Lake" },
        { min = 64, max = 66, result = "River" },
        { min = 67, max = 68, result = "Forest" },
        { min = 69, max = 70, result = "Hill" },
        { min = 71, max = 72, result = "Peak" },
        { min = 73, max = 75, result = "Woods" },
        { min = 76, max = 78, result = "Stream" },
        { min = 79, max = 80, result = "Clearing" },
        { min = 81, max = 82, result = "Mine" },
        { min = 83, max = 84, result = "Ritual site" },
        { min = 85, max = 86, result = "Monument" },
        { min = 87, max = 88, result = "Standing stones" },
        { min = 89, max = 90, result = "Watchtower" },
        { min = 91, max = 92, result = "Sinkhole" },
        { min = 93, max = 94, result = "Crater" },
        { min = 95, max = 96, result = "Shrine" },
        { min = 97, max = 98, result = "Crag" },
        { min = 99, max = 100, result = "Anomaly" },
    },
}

return M